config/routes.rb
Malstrom::Application.routes.draw do

  get 'samples/list'

  get 'threats/tags'

  get 'threats/ioc_list'

  get 'threats/profiles'

  get 'threats/analysis'

  get 'feeds/ioc'

  get 'feeds/import'

  post 'feeds/import' => "feeds#extract"
  resources :extract, :controller => "feeds"

  get 'feeds/list'

  get 'feeds/new_feed'

  post 'feeds/add_feed' => "feeds#create"
  resources :add_feed, :controller => "feeds"

  get 'feeds/run_feed' => "feeds#run_feed"
  resources :run_feed, :controller => "feeds"

  get 'feeds/delete_feed' => "feeds#delete_feed"
  resources :delete_feed, :controller => "feeds"

  get 'search/delete_iocs' => "search#delete_iocs"

  get 'search/indicators'

  get 'search/index'

  post 'search/index'

  post 'search/indicators' => "search#index"

  get "samples/list/yara" => 'samples#yara', :as => :samples_yara
  resources :yara, :controller => "samples"

  get "samples/download_malz", :to => "samples#download_malz"

  get "samples/list/upload" => 'samples#upload', :as => :samples_upload
  resources :upload, :controller => "samples"

  post "samples/list" => "samples#upload_malz"

  get 'samples/delete_sample' => "samples#delete_malz"
  resources :delete_malz, :controller => "samples"

  get "samples/analysis" => "samples#analysis"

  post "samples/add_note" => "samples#add_note"

  get "samples/remove_rule" => "samples#remove_rule"

  get "samples/new_yara" => "samples#new_yara"

  post "samples/save_sig" => "samples#process_sig"

  post "samples/addrule" => "samples#add_rule"

  #if Rails.env.production?
  #devise_for :users, :controllers => { :registrations => "registrations" } 
  #else
  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users
  #end

  root :to => "home#index"
  namespace :admin do
    get '/' => 'users#index'
    resources :users
  end
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  include ActionView::Helpers::TextHelper

  has_attached_file :malz,
                    :url  => "/assets/malware/:basename.:extension",
                    :path => ":rails_root/app/assets/malware/:basename.:extension"

  validates_attachment :malz,
                       :content_type => { :content_type => /^.*/ }
  validates_attachment_size :malz, :less_than => 10.megabytes
  # Allow tagging
  acts_as_taggable

  def samples
    render partial 'samples'
  end

  def signatures
    render partial 'signatures'
  end

  def upload
    render partial 'upload'
  end
end

app/controllers/samples_controller.rb
require 'digest'
require 'analyzer'
require 'hex_string'
require 'archive/zip'
require 'archive/zip/codec/traditional_encryption'

class SamplesController < ApplicationController
  before_action :authenticate_user!

  def list
    @all_malz = Sample.all
  end

  # malware downloads
  def download_malz
    file_name = params[:sample]
    base_name = File.basename(file_name, '.*')

    Archive::Zip.archive("tmp/#{base_name}.zip", # destination ZIP file
       "app/assets/malware/#{file_name}", # source file to add to ZIP
       #:encryption_codec => Archive::Zip::Codec::TraditionalEncryption, # encryption codec
       :password => 'infected') # ZIP password

    send_file "tmp/#{base_name}.zip", :type => 'application/octet-stream'

  end

  # malware upload function
  def upload_malz
    @sample = Sample.new( params[:sample] )
    @sample.malz = params[:malz]
    @sample.tag_list = params[:tag_list][:malz]
    if @sample.save
      if params[:box]
        if params[:passwd]
          unzipper(params[:sample], @sample.malz.path, params[:passwd][:box], params[:tag_list][:malz])
          @sample.malz.destroy
          @sample.delete
        else
          pass=''
          unzipper(params[:sample], @sample.malz.path, pass, params[:tag_list][:malz])
          @sample.malz.destroy
          @sample.delete
        end
        redirect_to samples_list_path, :notice => "Archive was extracted successfully!"
        return
      end
      redirect_to samples_list_path, :notice => "Sample was uploaded successfully!"
    end
    analyze = Analysis.new
    Thread.new { analyze.hashes(@sample.malz.path, @sample.malz_file_name) }
  end

  def unzipper(formdata, sample, zip_pass, tags)
    if zip_pass.length > 0
      if Archive::Zip.extract(sample, 'app/assets/malware', :password => zip_pass) do |zipfile|
        zipfile.each do |data|
          new_sample = Sample.create(formdata)
          new_sample.malz = File.open(data, 'rb')
          new_sample.tag_list = tags
          analyze = Analysis.new
          Thread.new { analyze.hashes(new_sample.malz.path, new_sample.malz_file_name) }
          end
        end
      end
    else
      if Archive::Zip.extract(sample) do |zipfile|
        zipfile.each do |data|
          new_sample = Sample.create(formdata)
          new_sample.malz = File.open(data, 'rb')
          new_sample.tag_list = tags
          analyze = Analysis.new
          Thread.new { analyze.hashes(new_sample.malz.path, new_sample.malz_file_name) }
          end
        end
      end
    end
  end

  # sample analysis function
  def analysis
    @sample = Sample.find_by_md5sum(params[:md5sum])
    contents = File.open(@sample.malz.path, 'rb')
    content = contents.read
    hex = content.to_hex_string
    magic = hex[0,5]
    scan = Analysis.new

    if magic == "4d 5a"
      @type = "PE"
      scan_results = scan.scan_pe(contents).html_safe
      @sample.deepdive = scan_results
    elsif magic == "ff d8"
      @type = "JPG"
      @page = scan.scan_jpg(content)
    elsif magic == "7f 45"
      @type = "ELF"
      @page = scan.scan_elf(content)
    elsif magic == "25 50"
      @type = "PDF"
      @page = "default"
    else
      @type = `file #{@sample.malz.path} | cut -d ':' -f 2`
      @page = "default"
    end
  end


  # parameterss for sample uploads
  def sample_params
    params.require(:sample).permit(:filename, :malz, :hash, :tags_list)
  end

  # malware removal function
  def delete_malz
    samps = Sample.find_by_id(params[:sample_id])
    samps.malz.destroy
    samps.delete
    redirect_to samples_list_path, :notice => "Sample deleted successfully!"
  end

  # add notes
  def add_note
    sample = Sample.find_by_id(params[:sample_id])
    note_contents = params[:note_content]
    sample.notes = note_contents
    if sample.save
      redirect_to samples_analysis_path(:md5sum => sample.md5sum), :notice => "Notes have been updated successfully!"
    else
      redirect_to samples_list_path, :alert => "Error: Could not save notes"
    end
  end

  # parameterss for notes
  def add_note_params
    params.require(:note_content, :sample_id)
  end

  # add yara signatures
  def add_rule
    new_rule_content = params[:rule_body]
    patt = 'rule.*\{'
    syntax_check = /#{patt}/.match(new_rule_content)
    if syntax_check.nil?
      redirect_to samples_list_path, :alert => "Syntax - 'rule <rulename> {' not found!"
      return
    end
    rule_name = params[:rule_name]
    new_rule_path = "app/assets/yara/#{rule_name}.yar"
    begin
      File.write(new_rule_path, new_rule_content)
      redirect_to samples_yara_path, :notice => "Signature has been uploaded successfully!"
    rescue
      redirect_to samples_yara_path, :alert => "Error: Could not create rule"
    end
  end

  # delete yara rule
  def remove_rule
    # delete rule here function here
    rule_name = params[:rule_name]
    rule_path = "app/assets/yara/#{rule_name}"
    begin
      File.delete(rule_path)
      redirect_to samples_yara_path, :notice => "Signature has been deleted successfully!"
    rescue
      redirect_to samples_yara_path, :alert => "Could not delete rule"
    end
  end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_signatures.html.erb
<div id="signature" class="center box tab-pane">
  <form id="frm-url" class="margin-all-0" action="/en/url/submission/" method="post">
    <div style='display:none'><input type='hidden' name='csrfmiddlewaretoken' value='b11b37ca126cb5e4a7fbd8a9e1ae5817' /></div>
    <div class="url-chooser center" style="margin-bottom:28px">
      <input id="url" type="text" name="url" placeholder="http://www.example.com/">
          <span class="url" style="-moz-user-select: none;">
          </span>
          <span id="url" class="action" style="-moz-user-select: none;">
            Enter URL
          </span>
    </div>

    <div class="margin-top-1">
      <button id="btn-scan-url" class="btn btn-primary start xlarge"
              type="submit">Scan it!</button>
    </div>
  </form>
</div>

app/views/samples/_upload.html.erb
<style type="text/css"> .centerDiv { width: 17%; height:100px; margin: 0 auto;  text-align: center;} </style>

<div class="tab-pane active" id="#upload">
  <div class="container">
    <!-- Default panel contents -->
    <h4><span class="glyphicon glyphicon-upload"></span> Upload new samples:</h4>
      <div class="container">
      <%= form_tag @sample, html: {action: :upload_malz}, multipart: true do %>
          <%= file_field_tag 'malz' %>
        <h5><span class="glyphicon glyphicon-compressed"></span> Compressed?</h5>
        <div class="row">
          <div class="col-lg-6">
            <div class="input-group">
          <span class="input-group-addon">
            <%= check_box_tag(:box) %>
            <%= label_tag(:box, "Unzip") %>
         </span>
              <%= text_field(:passwd, :box, :class => "form-control", :placeholder => "password (if encrypted)") %>
            </div>
          </div><!-- /.col-lg-6 -->
        </div>
        <h5><span class="glyphicon glyphicon-tags"></span> Tags</h5>
        <div class="row">
          <div class="col-lg-6">
            <div class="input-group">
              <%= text_field(:tag_list, :malz, :class => "form-control", :placeholder => "Max++, Rootkit, APT") %>
                <span class="input-group-btn">
                    <%= submit_tag("Upload", class: "btn btn-primary")%>
                </span>
            </div><!-- /input-group -->
          </div><!-- /.col-lg-6 -->
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/samples/_yara.html.erb
<style type="text/css"> .centerDiv { width: 17%; height:20px; margin: 0 auto;  text-align: center;} </style>

<div class="tab-pane active" id="#signatures">
    <div class="container">
    <h5>Add new yara signature <%= link_to '', samples_new_yara_path, :class => 'glyphicon glyphicon-plus btn btn-success' %></h5>
    <!--<h5>Scan samples with available rules <%# link_to '', samples_list_path, :class => 'glyphicon glyphicon-refresh btn btn-info' %></h5>-->
      </div>
  <% @rules = Dir["app/assets/yara/*.yar"] %>
  <div class="container">
    <!-- Default panel contents -->
    <div class="panel panel-default">
    <div class="panel-heading">Rule Sets</div>
    <table class="table table-striped">
        <thead>
        <tr>
          <th>Name</th>
          <th>Remove</th>
        </tr>
        </thead>
        <tbody>
        <% sig_id = 0 %>
        <% @rules.each do |x| %>
            <% sig_id += 1 %>
            <tr>
            <td><button type="button" class="btn btn-info" data-toggle="modal" data-target="#<%= sig_id.to_s %>"><%= File.basename(x) %></button></td>
            <!-- Modal -->
                <div class="modal fade" id="<%= sig_id.to_s %>" tabindex="-1" role="dialog" aria-labelledby="editLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="editLabel">Rule Viewer</h4>
                        </div>
                        <div class="modal-body">
                            <form role="form" action="add_rule" enctype="multipart/form-data" method="post" onsubmit="window.location.reload();">
                            <input type="text" class="form-control" name="rule_name" value="<%= File.basename(x) %>" />
                            <textarea class="form-control" rows="10" name="rule_text" id="content"><%= File.open(x, 'rb').read %></textarea>
                            <!--<button type="submit" class="btn btn-primary" name="new" value="New">Save</button>-->
                            </form>
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                        </div>
                    </div>
                </div>
            <td><%= link_to '', samples_remove_rule_path(:rule_name => File.basename(x)), :class => "btn btn-danger glyphicon glyphicon-trash" %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>

app/views/samples/analysis.html.erb
<h3>File: <%= @sample.malz_file_name %></h3>

 <div class="col-xs-7" style="float">
  <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading">Details</div>
    <!-- List group -->
    <ul class="list-group">
      <li class="list-group-item">Type: <%= @type %></li>
      <li class="list-group-item">Size: <%= @sample.malz_file_size %></li>
      <li class="list-group-item">MD5: <%= @sample.md5sum %></li>
      <li class="list-group-item">SHA1: <%= @sample.sha1sum %></li>
      <li class="list-group-item">SHA256: <%= @sample.sha256 %></li>
    </ul>
  </div>
   <div class="panel panel-default">
     <div class="panel-heading">
       <h3 class="panel-title">Analysis</h3>
     </div>
     <div class="panel-body">
       <div class="well well-lg" style="float">
         <%= @sample.deepdive %>
       </div>
     </div>
   </div>
 </div>

  <div class="col-xs-2" style="float">
    <div class="panel panel-danger">
      <div class="panel-body">
        <h5>
          Virustotal Detection:  <%= link_to @sample.detection, "http://virustotal.com/en/file/#{@sample.sha256}/analysis", :target => "_blank", :class => "label label-danger" %>
        </h5>
      </div>
    </div>
  </div>

<div class="col-xs-4" style="float">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Notes</h3>
    </div>
    <div class="panel-body">
      <%= form_tag("add_note", method: "post") do %>
          <%= label_tag(:add_note, '') %>
          <div>
            <%= text_area_tag(:note_content, "#{@sample.notes}", size: "52x15") %>
            <%= hidden_field_tag(:sample_id, @sample.id) %>
          </div>
          <div>
            <%= submit_tag("Save", class: "btn btn-primary") %>
          </div>
          <% end %>
    </div>
  </div>
</div>

app/views/samples/list.html.erb
<head>
    <h2 align="left">
        <%= image_tag("biohazard-orb.png", :size => "100x60", :style => "float :left",:crop => :fill) %>
      <b>Malware Samples </b><td><button type="button" class="btn btn-success glyphicon glyphicon-plus" data-toggle="modal" data-target="#upload-modal"></button></td>

    </h2>
</head>
  <div class="container-fluid">
    <div class="panel panel-default">
      <div class="panel-heading">
        <table id="sample_table" class="display table">
          <thead>
          <tr>
            <th>DL</th>
            <th>MD5</th>
            <th>MIME</th>
            <th>Detected</th>
            <th>Remove</th>
            <th>Tags</th>
          </tr>
          </thead>
          <tbody>
          <tr>
          <% @all_malz.each do |mal| %>
              <td><%= link_to '', samples_download_malz_path(:sample => mal.malz_file_name), :class => 'glyphicon glyphicon-download-alt btn btn-primary' %></td>
              <td><%= link_to mal.md5sum, samples_analysis_path(:md5sum => mal.md5sum) %></td>
              <td><%= mal.malz_content_type %></td>
              <% if mal.detection == 'N/A' %>
                  <td><%= mal.detection %></td>
              <% else %>
                  <td><%= link_to mal.detection, "http://virustotal.com/en/file/#{mal.sha256}/analysis", :target => "_blank" %></td>
              <% end %>
              <td><%= link_to '', samples_delete_sample_path(:sample_id => mal.id), class: 'glyphicon glyphicon-trash btn btn-danger' %></td>
              <% mal.tag_list.each do |tag| %>
                  <td><%= link_to tag, threats_ioc_list_path(:tag => tag), :class => 'label label-large label-info' %></td>
              <% end %>
              </tr>
              </tbody>
          <% end %>
          </table>
      </div>
    </div>
  </div>

<!-- Modal -->
<div class="modal fade" id="upload-modal" tabindex="-1" role="dialog" aria-labelledby="editLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="editLabel">Sample Upload</h4>
      </div>
      <div class="modal-body">
        <div class="well">
        <%= form_tag @sample, html: {action: :upload_malz}, multipart: true do %>
            <%= file_field_tag 'malz' %>
            <!--<h5><span class="glyphicon glyphicon-compressed"></span> Compressed?</h5>
            <div class="row">
              <div class="col-lg-6">
                <div class="input-group">
          <span class="input-group-addon">
            <%# check_box_tag(:box) %>
            <%# label_tag(:box, "Unzip") %>
         </span>
                  <%# text_field(:passwd, :box, :class => "form-control", :placeholder => "password") %>
                </div>
              </div><!-- /.col-lg-6 -->
            <!--</div>-->
            <h5><span class="glyphicon glyphicon-tags"></span> Tags</h5>
            <div class="row">
              <div class="col-lg-6">
                <div class="input-group">
                  <%= text_field(:tag_list, :malz, :class => "form-control", :placeholder => "Max++, Rootkit, APT") %>
                  <span class="input-group-btn">
                    <%= submit_tag("Upload", :class => "btn btn-primary")%>
                </span>
                </div><!-- /input-group -->
              </div><!-- /.col-lg-6 -->
            </div>
        <% end %>
       </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/samples/new_yara.html.erb
<div class="container" style="float:left">
  <h4>Compose Yara Signature</h4>
  <%= form_tag("addrule", method: "post") do %>
      <%= label_tag(:q, '') %>
      <div>
        <h5>Rule Name:</h5><%= text_field_tag(:rule_name, '') %>.yar
      </div>
      <h5>Rule Content</h5>
      <div>
      <%= text_area_tag(:rule_body, '', size: "100x15") %>
      </div>
      <div>
        <%= submit_tag("Save", class: "btn btn-primary") %>
      </div>
  <% end %>
</div>

app/views/samples/samples.html.erb
<div id="samples" class="center box tab-pane active">
  <form id="frm-file" class="margin-all-0" action="/en/file/upload/" method="post" enctype="multipart/form-data">
    <div class="file-chooser center">
      <input id="file-choosen" type="file" name="file" size="50">
          <span id="file-name" class="file-name" style="-moz-user-select: none;text-align:left;">
            No file selected
          </span>
          <span class="action" style="-moz-user-select:none;">
            Choose File
          </span>
    </div>
  </form>

  <div class="text-gray">Maximum file size: 64MB</div>

  <div class="margin-top-2 vt-width-60 text-gray">

    By clicking 'Scan it!', you consent to our
    <a href="/en/about/terms-of-service/">Terms of Service</a>
    and allow VirusTotal to <br>
    share this file with the security community.
    See our <a href="/en/about/privacy/">Privacy Policy</a>
    for details.

  </div>

  <div class="margin-top-3">
    <button id="btn-scan-file"
            class="btn btn-primary start xlarge"
            type="submit">Scan it!</button>
  </div>
</div>

app/views/samples/signatures.html.erb
<div id="signature" class="center box tab-pane">
  <form id="frm-url" class="margin-all-0" action="/en/url/submission/" method="post">
    <div style='display:none'><input type='hidden' name='csrfmiddlewaretoken' value='b11b37ca126cb5e4a7fbd8a9e1ae5817' /></div>
    <div class="url-chooser center" style="margin-bottom:28px">
      <input id="url" type="text" name="url" placeholder="http://www.example.com/">
          <span class="url" style="-moz-user-select: none;">
          </span>
          <span id="url" class="action" style="-moz-user-select: none;">
            Enter URL
          </span>
    </div>

    <div class="margin-top-1">
      <button id="btn-scan-url" class="btn btn-primary start xlarge"
              type="submit">Scan it!</button>
    </div>
  </form>
</div>

app/views/samples/upload.html.erb
<style type="text/css"> .centerDiv { width: 17%; height:100px; margin: 0 auto;  text-align: center;} </style>

<div class="tab-pane active" id="#upload">
  <div class="container">
    <!-- Default panel contents -->
    <h4><span class="glyphicon glyphicon-upload"></span> Upload new samples:</h4>
      <div class="container">
      <%= form_tag @sample, html: {action: :upload_malz}, multipart: true do %>
          <%= file_field_tag 'malz' %>
        <h5><span class="glyphicon glyphicon-compressed"></span> Compressed?</h5>
        <div class="row">
          <div class="col-lg-6">
            <div class="input-group">
          <span class="input-group-addon">
            <%= check_box_tag(:box) %>
            <%= label_tag(:box, "Unzip") %>
         </span>
              <%= text_field(:passwd, :box, :class => "form-control", :placeholder => "password (if encrypted)") %>
            </div>
          </div><!-- /.col-lg-6 -->
        </div>
        <h5><span class="glyphicon glyphicon-tags"></span> Tags</h5>
        <div class="row">
          <div class="col-lg-6">
            <div class="input-group">
              <%= text_field(:tag_list, :malz, :class => "form-control", :placeholder => "Max++, Rootkit, APT") %>
                <span class="input-group-btn">
                    <%= submit_tag("Upload", class: "btn btn-primary")%>
                </span>
            </div><!-- /input-group -->
          </div><!-- /.col-lg-6 -->
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/samples/yara.html.erb
<style type="text/css"> .centerDiv { width: 17%; height:20px; margin: 0 auto;  text-align: center;} </style>

<div class="container-fluid">
  <%= image_tag("yara_old-logo.png", :size => "120x150", :style => "float :left",:crop => :fill) %>

  <h5>Add new yara signature <%= link_to '', samples_new_yara_path, :class => 'glyphicon glyphicon-plus btn btn-success' %></h5>
    <!--<h5>Scan samples with available rules <%# link_to '', samples_list_path, :class => 'glyphicon glyphicon-refresh btn btn-info' %></h5>-->
  <% @rules = Dir["app/assets/yara/*.yar"] %>
  <div class="container">
    <!-- Default panel contents -->
    <div class="panel panel-default">
    <div class="panel-heading">Rule Sets</div>
    <table class="table table-striped">
        <thead>
        <tr>
          <th>Name</th>
          <th>Remove</th>
        </tr>
        </thead>
        <tbody>
        <% sig_id = 0 %>
        <% @rules.each do |x| %>
            <% sig_id += 1 %>
            <tr>
            <td><button type="button" class="btn btn-info" data-toggle="modal" data-target="#<%= sig_id.to_s %>"><%= File.basename(x) %></button></td>
            <!-- Modal -->
                <div class="modal fade" id="<%= sig_id.to_s %>" tabindex="-1" role="dialog" aria-labelledby="editLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                            <h4 class="modal-title" id="editLabel">Rule Viewer</h4>
                        </div>
                        <div class="modal-body">
                            <form role="form" action="add_rule" enctype="multipart/form-data" method="post" onsubmit="window.location.reload();">
                            <input type="text" class="form-control" name="rule_name" value="<%= File.basename(x) %>" />
                            <textarea class="form-control" rows="10" name="rule_text" id="content"><%= File.open(x, 'rb').read %></textarea>
                            <!--<button type="submit" class="btn btn-primary" name="new" value="New">Save</button>-->
                            </form>
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                        </div>
                    </div>
                </div>
            <td><%= link_to '', samples_remove_rule_path(:rule_name => File.basename(x)), :class => "btn btn-danger glyphicon glyphicon-trash" %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>