config/routes.rb
Malstrom::Application.routes.draw do

  get 'samples/list'

  get 'threats/tags'

  get 'threats/ioc_list'

  get 'threats/profiles'

  get 'threats/analysis'

  get 'feeds/ioc'

  get 'feeds/import'

  post 'feeds/import' => "feeds#extract"
  resources :extract, :controller => "feeds"

  get 'feeds/list'

  get 'feeds/new_feed'

  post 'feeds/add_feed' => "feeds#create"
  resources :add_feed, :controller => "feeds"

  get 'feeds/run_feed' => "feeds#run_feed"
  resources :run_feed, :controller => "feeds"

  get 'feeds/delete_feed' => "feeds#delete_feed"
  resources :delete_feed, :controller => "feeds"

  get 'search/delete_iocs' => "search#delete_iocs"

  get 'search/indicators'

  get 'search/index'

  post 'search/index'

  post 'search/indicators' => "search#index"

  get "samples/list/yara" => 'samples#yara', :as => :samples_yara
  resources :yara, :controller => "samples"

  get "samples/download_malz", :to => "samples#download_malz"

  get "samples/list/upload" => 'samples#upload', :as => :samples_upload
  resources :upload, :controller => "samples"

  post "samples/list" => "samples#upload_malz"

  get 'samples/delete_sample' => "samples#delete_malz"
  resources :delete_malz, :controller => "samples"

  get "samples/analysis" => "samples#analysis"

  post "samples/add_note" => "samples#add_note"

  get "samples/remove_rule" => "samples#remove_rule"

  get "samples/new_yara" => "samples#new_yara"

  post "samples/save_sig" => "samples#process_sig"

  post "samples/addrule" => "samples#add_rule"

  #if Rails.env.production?
  #devise_for :users, :controllers => { :registrations => "registrations" } 
  #else
  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users
  #end

  root :to => "home#index"
  namespace :admin do
    get '/' => 'users#index'
    resources :users
  end
end

app/models/feeds.rb
class Feeds < ActiveRecord::Base
  # Allows tagging
  acts_as_taggable
end

app/controllers/feeds_controller.rb
require 'find_artifacts'
require 'docsplit'

class FeedsController < ApplicationController
  before_action :authenticate_user!

  def list
    # Local var for Feed listing
    @feeds = Feeds.all
  end

  def feed_params
    params.require(:feeds).permit(:name, :url, :tag_list)
  end

  def new_feed
    @add_feed = Feeds.new
  end

  def create
    @add_feed = Feeds.new(feed_params)
    if @add_feed.save
      redirect_to :feeds_list, :notice => "Feed has been saved successfully!"
    else
      flash.now[:alert] = "Error: Feed can not be saved"
      render :feeds_new_feed_path
    end
  end

  def run_feed
    update = Updater.new
    # New job for feed update
    Thread.new { update.retrieval(params[:url], params[:tags]) }
    # Redirect upon job initiation
    if update
      redirect_to :feeds_list, :notice => "Feed update initiated!"
    else
      flash.now[:alert] = "Error: Cannot run feed at this time"
      render :feeds_list_path
    end
  end
  helper_method :update_feed

  def delete_feed
    @feedname = Feeds.find_by_name(params[:name]).delete
    if @feedname
      redirect_to :feeds_list, :notice => "Feed deleted successfully!"
    else
      flash.now[:alert] = "Error: Cannot delete feed at this time"
      render :feeds_list_path
    end
  end
  helper_method :delete_feed

  def scheduler
    # function to keep track of feed scheduling
  end

  def extract
    # function to import indicators of compromise
    extractor = FindArtifacts.new
    file_name = params[:ioc_set].original_filename
    file_data = params[:ioc_set].tempfile.open.read
    tmp_path = "tmp/docsplit/#{file_name}"
    tags = params[:tag_list][:upload_ioc]

    # Save uploaded IOC report
    File.open(tmp_path, 'wb') { |file| file.write("#{file_data}") }
    # Extract text
    Docsplit.extract_text(tmp_path, :ocr => false, :output => 'tmp/docsplit')

    # Open TXT file
    base_name = file_name.split('.')[0]
    data_path = "tmp/docsplit/#{base_name}"
    data = File.open("#{data_path}.txt", 'rb').read

    # New jobs for IOC import
    Thread.new { extractor.ipv4(data, tags) }
    Thread.new { extractor.domain(data, tags) }
    Thread.new { extractor.md5(data, tags) }

    if data
      #File.delete(tmp_path)
      #File.delete(file_name)
      redirect_to :feeds_import, :notice => "IOC's are being processed!"
    else
      flash.now[:alert] = "Error: IOC file could not be processed"
      redirect_to :feeds_import
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper

end

app/views/feeds/feeds.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Feeds</title>
  <h1>Feeds</h1>
</head>
<body>
<div class="span9">
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th>Last Update</th>
    <th>Run Now</th>
  </tr>
  </thead>
  <tbody>
  <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= feed.url %></td>
        <td><%= feed.last_updated %></td>
        <td>'link to run feed'</td>
      </tr>
  <% end %>
  </tbody>
</table>
</div>
</body>
</html>

app/views/feeds/import.html.erb
<div class="well">
  <!-- Default panel contents -->
  <h4><span class="glyphicon glyphicon-cloud-upload"></span> Import IOC set:</h4>
    <%= form_tag @extract, html: {action: :upload_ioc}, multipart: true do %>
        <%= file_field_tag 'ioc_set' %>
      <div class="well well-sm">
        <div class="alert alert-info" role="alert"><strong>Supported File Formats:</strong> TXT, CSV, XML, and PDF</div>
      </div>
        <h5><span class="glyphicon glyphicon-tags"></span> Tags</h5>
        <div class="row">
          <div class="col-lg-6">
            <div class="input-group">
              <%= text_field(:tag_list, :upload_ioc, :class => "form-control", :placeholder => "Putter Panda, APT, from report") %>
              <span class="input-group-btn">
                    <%= submit_tag("Import", class: "btn btn-primary")%>
                </span>
            </div><!-- /input-group -->
          </div><!-- /.col-lg-6 -->
        </div>
    <% end %>
</div>

app/views/feeds/ioc.html.erb
<h2>IOC Analysis</h2>

app/views/feeds/list.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Feeds</title>
  <h4>
    <%= image_tag("rss_cube.png", :size => "65x35", :style => "float :left",:crop => :fill) %>
    Add Threat Feed <%= link_to '', feeds_new_feed_path, class: 'glyphicon glyphicon-plus btn btn-success' %>
  </h4>
</head>
  <body>
    <div class="col-xs-12">
    <div class="panel panel-success">
    <table id="feed_table" class="table table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>URL</th>
        <th>Run Now</th>
        <!--<th>Scheduler</th>-->
        <th>Remove</th>
        <th>Tags</th>
    </tr>
    </thead>
    <tbody>
        <% @feeds.each do |feed| %>
        <tr>
            <td><%= feed.name %></td>
            <td><%= feed.url %></td>
            <td><%= link_to '', feeds_run_feed_path(:url => feed.url, :name => feed.name, :tags => feed.tag_list), class: 'glyphicon glyphicon-retweet btn btn-primary' %></td>
            <!--<td><label class="switch-toggle well">
              <input type="checkbox">
              <span>
              <span>Off</span>
              <span>On</span>
              </span>
              <a class="btn btn-success active"></a>
            </label></td>-->
            <td><%= link_to '', feeds_delete_feed_path(:name => feed.name), class: 'glyphicon glyphicon-trash btn btn-danger' %></td>
            <% feed.tag_list.each do |tag| %>
            <td><%= link_to tag, threats_ioc_list_path(:tag => tag), :class => 'label label-large label-info' %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
    </table>
    </div>
    </div>
  </body>
</html>

app/views/feeds/new_feed.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Add Feed</title>
  <div class="h2">
    Feed Builder
    <span class="glyphicon glyphicon-wrench"></span>
  </div>
</head>
<body>
<div class="authform pull-left">
    <%= form_for @add_feed, url: {:action => "create"} do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :autofocus => true, class: 'form-control'  %>
          </div>
          <div class="form-group">
            <%= f.label :url %>
            <%= f.text_field :url, :autofocus => true, class: 'form-control'  %>
          </div>
          <div class="form-group">
            <%= f.label :tag_list %>
            <%= f.text_field :tag_list, :autofocus => true, class: 'form-control'  %>
          </div>
            <%= f.submit :class => "btn btn-primary" %>
    <% end %>
</div>
</body>
</html>