config/routes.rb
Malstrom::Application.routes.draw do

  get 'samples/list'

  get 'threats/tags'

  get 'threats/ioc_list'

  get 'threats/profiles'

  get 'threats/analysis'

  get 'feeds/ioc'

  get 'feeds/import'

  post 'feeds/import' => "feeds#extract"
  resources :extract, :controller => "feeds"

  get 'feeds/list'

  get 'feeds/new_feed'

  post 'feeds/add_feed' => "feeds#create"
  resources :add_feed, :controller => "feeds"

  get 'feeds/run_feed' => "feeds#run_feed"
  resources :run_feed, :controller => "feeds"

  get 'feeds/delete_feed' => "feeds#delete_feed"
  resources :delete_feed, :controller => "feeds"

  get 'search/delete_iocs' => "search#delete_iocs"

  get 'search/indicators'

  get 'search/index'

  post 'search/index'

  post 'search/indicators' => "search#index"

  get "samples/list/yara" => 'samples#yara', :as => :samples_yara
  resources :yara, :controller => "samples"

  get "samples/download_malz", :to => "samples#download_malz"

  get "samples/list/upload" => 'samples#upload', :as => :samples_upload
  resources :upload, :controller => "samples"

  post "samples/list" => "samples#upload_malz"

  get 'samples/delete_sample' => "samples#delete_malz"
  resources :delete_malz, :controller => "samples"

  get "samples/analysis" => "samples#analysis"

  post "samples/add_note" => "samples#add_note"

  get "samples/remove_rule" => "samples#remove_rule"

  get "samples/new_yara" => "samples#new_yara"

  post "samples/save_sig" => "samples#process_sig"

  post "samples/addrule" => "samples#add_rule"

  #if Rails.env.production?
  #devise_for :users, :controllers => { :registrations => "registrations" } 
  #else
  devise_for :users, :path_names => {:sign_in => "login", :sign_out => "logout"}, :path => "d"
  resources :users
  #end

  root :to => "home#index"
  namespace :admin do
    get '/' => 'users#index'
    resources :users
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("malstrom_icon1.png",:size => "45x45"), root_path) %>
       </div>

       <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li><%= render 'layouts/navigation_links' %></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
              <li><%= render 'layouts/navigation_links2' %></li>
            </ul>

    <% else %>
    <!--
        <div class="collapse navbar-collapse pull-right" role="navigation">
          <div>
            <ul class="nav navbar-nav pull-left">
              <li><%# link_to 'Register', new_user_registration_path %></li>
              <li><%#= link_to '', new_user_session_path, :class => 'navbar-brand glyphicon glyphicon-log-in glyphicon-white' %></li>
            </ul>
          </div>
        </div>-->
    <% end %>
  </div>
</nav>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="footer">
    <div class="text-center">
      <p><span class="glyphicon glyphicon-info-sign"></span> Innovation Project 2015. Developed by <a href="http://t3chm3chanics.wix.com/bdargenbright" target="_blank">byt3smith</a>.</p>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
    <li><%= link_to 'Samples', samples_list_path, :id => "#samplelist", :class => "Samples" %></li>
    <li></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">IOC <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to ' Search', search_indicators_path, :class => "glyphicon glyphicon-search" %></li>
        <li><%= link_to ' Feeds', feeds_list_path, :class => "glyphicon glyphicon-import" %></li>
        <li><%= link_to ' Import', feeds_import_path, :class => "glyphicon glyphicon-cloud-upload" %></li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tools <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to ' Tags', threats_tags_path, :class => "glyphicon glyphicon-tags" %></li>
        <li><%= link_to ' Profiles', threats_profiles_path, :class => "glyphicon glyphicon-user" %></li>
        <li class="divider"></li>
        <li><%= link_to ' YARA', samples_yara_path, :class => "glyphicon glyphicon-list" %></li>
      </ul>
    </li>
<% else %>
  <li><%= button_to 'Login', new_user_session_path %></li>
<% end %>

app/views/layouts/_navigation_links2.html.erb
<% if user_signed_in? %>
    <script>
        $('#element').tooltip('show')
    </script>
    <li><%= link_to '', edit_user_registration_path, :class => 'navbar-brand glyphicon glyphicon-cog', :data => {:toggle=>"tooltip"}, :title => "Edit Account" %></li>
    <p class="navbar-text">Logged in as: <%= current_user.name %></p>
    <li><%= button_to 'Logout', destroy_user_session_path, :method=>'delete', :class => 'btn btn-default navbar-btn' %></li>
<% else %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Mssd" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mssd" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main">
  <%= render 'layouts/messages' %>
  <%= yield %>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  <% end %>

  <% if user_signed_in? %>
      <% #link_to "My Profile", user_root_path%>
      <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
  <%end%>
</main>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Malstrom" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mssd" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
      <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <% end %>
    </main>
  </body>
</html>